export const INICIAR_SESION = 'INICIAR_SESION';
export const CERRAR_SESION = 'CERRAR_SESION';

export const OBTENER_CLIENTES = 'OBTENER_CLIENTES';
export const AGREGAR_CLIENTE = 'AGREGAR_CLIENTE';
export const ELIMINAR_CLIENTE = 'ELIMINAR_CLIENTE';

export const CLIENTE_ACTUAL = 'CLIENTE_ACTUAL';

export const OBTENER_DIRECCIONES = 'OBTENER_DIRECCIONES';
export const AGREGAR_DIRECCION = 'AGREGAR_DIRECCION';
export const EDITAR_DIRECCION = 'EDITAR_DIRECCION';
export const ELIMINAR_DIRECCION = 'ELIMINAR_DIRECCION';


export const OBTENER_DATOSCONTACTO = 'OBTENER_DATOSCONTACTO';
export const AGREGAR_CONTACTO = 'AGREGAR_CONTACTO';
export const EDITAR_CONTACTO = 'EDITAR_CONTACTO';
export const ELIMINAR_CONTACTO = 'ELIMINAR_CONTACTO';




