export const OBTENER_CLIENTES = 'OBTENER_CLIENTES';
export const AGREGAR_CLIENTE = 'AGREGAR_CLIENTE';

export const CLIENTE_ACTUAL = 'CLIENTE_ACTUAL';

export const OBTENER_DIRECCIONES = 'OBTENER_DIRECCIONES';
export const OBTENER_DATOSCONTACTO = 'OBTENER_DATOSCONTACTO';

